# fly.toml app configuration file generated for back-patient-lake-2960 on 2024-07-04T15:50:05+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'back-patient-lake-2960'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.http]
    type = "http"
    port = 3000
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/health_check"
    headers = { "User-Agent" = "Fly-HealthCheck" }

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/app/public'
  url_prefix = '/'

[env]
  REDIS_URL = "redis://redis:6379/0"
